name: build_local_dashboard
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  generate-dashboard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
      # RENV_PATHS_ROOT: ${{ github.repository }}/docs/.renv
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      # Downloading both the repositories to simulate the original task
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - uses: r-lib/actions/setup-r@v2
      - run: echo "💡 The ${{ github.repository }} repository have been cloned to the runner."
      - name: Checkout
        uses: actions/checkout@v3        
      - name: build local repository
        working-directory: ${{ github.workspace }}
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::init()	
          install.packages('remotes')
          remotes::install_github('uva-bi-sdad/community')
          source("build.R")          
          renv::snapshot()
      - name: List files
        run: |
          ls -la                  
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
