name: build_local_dashboard
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  generate-dashboard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
      RENV_PATHS_ROOT: ${{ github.repository }}/docs/.renv
    steps:
      # Downloading both the repositories to simulate the original task
      - uses: actions/checkout@main
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.RENV_PATHS_ROOT }}
            ${{ github.repository }}/docs
          key: ${{ runner.os }}-renv-${{ hashFiles('docs/*') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - uses: r-lib/actions/setup-r@v2
      - run: echo "💡 The ${{ github.repository }} repository have been cloned to the runner."
      - name: build local repository
        working-directory: ${{ github.workspace }}
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::init()	
          renv::restore()	
          install.packages('remotes')
          remotes::install_github('uva-bi-sdad/community')
          source("build.R")
          renv::snapshot()
      - name: List files
        run: |
          ls -la
      # - name: Commit files # Commit changes
      #   working-directory: annoying/auto_vdh
      #   run: |
      #     ls -la
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add -A
      #     git commit -m "generating dashboard"
      #     git push origin main:dashboard -f
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
